In [3]:
import numpy as np

In [5]:
np.random.randint(18,21,200)

array([19, 18, 19, 18, 18, 18, 19, 19, 20, 19, 19, 19, 19, 18, 20, 19, 19,
       18, 20, 20, 19, 19, 18, 18, 20, 19, 20, 18, 18, 18, 20, 20, 18, 18,
       20, 18, 20, 20, 18, 19, 20, 19, 18, 19, 19, 19, 20, 19, 18, 18, 18,
       18, 20, 19, 18, 18, 18, 20, 20, 19, 18, 18, 18, 20, 18, 19, 20, 18,
       19, 19, 18, 20, 18, 20, 18, 20, 20, 20, 18, 18, 20, 20, 18, 18, 20,
       18, 20, 19, 18, 18, 19, 18, 19, 18, 19, 20, 19, 19, 18, 19, 19, 20,
       19, 19, 18, 20, 18, 18, 20, 19, 19, 19, 19, 20, 19, 19, 19, 20, 18,
       20, 20, 18, 20, 20, 20, 20, 20, 18, 18, 19, 20, 18, 18, 20, 20, 19,
       18, 19, 20, 18, 19, 18, 20, 18, 20, 19, 18, 20, 18, 18, 20, 20, 20,
       20, 20, 18, 19, 19, 20, 19, 18, 19, 20, 18, 18, 18, 18, 18, 20, 18,
       20, 18, 20, 19, 20, 18, 19, 20, 19, 20, 20, 19, 19, 19, 19, 18, 19,
       18, 19, 19, 20, 20, 20, 19, 19, 18, 19, 18, 20, 19])

In [7]:
h=[30,20,5,8,9]
h

[30, 20, 5, 8, 9]

In [23]:
s=(6,2,3,9,7,5,8)
s

(6, 2, 3, 9, 7, 5, 8)

In [29]:
tuple(x**2 for x in s)

(36, 4, 9, 81, 49, 25, 64)

In [31]:
y=list(s)
k=[]
for i in y:
    k.append(i**2)
    s=tuple(k)
    s

In [33]:
s

(36, 4, 9, 81, 49, 25, 64)

In [40]:
m=[]
for i in s:
    if i>30:
        m.append(i)

In [38]:
m

[36, 81, 49, 64]

In [42]:
arr=np.array([20,50,30,70,80,40,36,54,23,98])

In [44]:
arr

array([20, 50, 30, 70, 80, 40, 36, 54, 23, 98])

In [46]:
arr+5

array([ 25,  55,  35,  75,  85,  45,  41,  59,  28, 103])

In [48]:
 arr**2

array([ 400, 2500,  900, 4900, 6400, 1600, 1296, 2916,  529, 9604])

In [50]:
arr

array([20, 50, 30, 70, 80, 40, 36, 54, 23, 98])

In [52]:
arr>50

array([False, False, False,  True,  True, False, False,  True, False,
        True])

In [54]:
arr[arr>50]

array([70, 80, 54, 98])

In [56]:
arr

array([20, 50, 30, 70, 80, 40, 36, 54, 23, 98])

In [58]:
arr[4]

80

In [60]:
arr

array([20, 50, 30, 70, 80, 40, 36, 54, 23, 98])

In [62]:
arr[arr<]

[36, 4, 9, 81, 49, 25, 64]